# Generated by Django 6.0.8 on 2026-09-25 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryReferenceCounter',
            fields=[
                ('period', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('contact', 'Contact form'), ('booking', 'Booking request')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('interest', models.CharField(blank=True, default='', max_length=60)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(blank=True, default='', max_length=3)),
                ('message', models.TextField(blank=True, default='')),
                ('tour_title', models.CharField(blank=True, default='', max_length=140)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('guests', models.JSONField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('quoted', 'Quoted'), ('won', 'Booked'), ('lost', 'Closed')], db_index=True, default='new', max_length=12)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='website', max_length=40)),
                ('is_sample', models.BooleanField(default=False, help_text='Demo enquiry created by the seed.')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalog.tour')),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status change'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('note', 'Note'), ('contacted', 'Contacted')], max_length=16)),
                ('actor_name', models.CharField(blank=True, max_length=120, null=True)),
                ('summary', models.CharField(max_length=300)),
                ('note', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status', 'created_at'], name='enquiries_e_status_91f4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['assignee', 'status'], name='enquiries_e_assigne_fe86c4_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiryevent',
            index=models.Index(fields=['enquiry', 'created_at'], name='enquiries_e_enquiry_dd329a_idx'),
        ),
    ]
