# Generated by Django 6.0.8 on 2026-09-25 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('question', models.CharField(max_length=240, unique=True)),
                ('answer', models.TextField()),
                ('group', models.CharField(choices=[('general', 'General'), ('booking', 'Booking'), ('travel', 'Travel'), ('payment', 'Payment')], default='general', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='primary', max_length=20, unique=True)),
                ('hero', models.JSONField(default=dict)),
                ('hero_slides', models.JSONField(default=list)),
                ('values', models.JSONField(default=list)),
                ('contact', models.JSONField(default=dict)),
                ('socials', models.JSONField(default=dict)),
                ('newsletter', models.JSONField(default=dict)),
                ('footer_blurb', models.TextField(blank=True, default='')),
                ('video', models.JSONField(default=dict)),
                ('seo', models.JSONField(default=dict)),
                ('promo', models.JSONField(default=dict)),
                ('about', models.JSONField(default=dict)),
                ('home', models.JSONField(default=dict)),
                ('pages', models.JSONField(default=dict)),
                ('notice', models.JSONField(default=dict)),
                ('brand', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='compass', max_length=40)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('cta_label', models.CharField(blank=True, default='', max_length=60)),
                ('cta_href', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('author_name', models.CharField(default='Holidaybank Expeditions', max_length=120)),
                ('author_avatar', models.CharField(blank=True, default='', max_length=500)),
                ('reading_minutes', models.PositiveIntegerField(default=4)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('featured', models.BooleanField(default=False)),
                ('seo', models.JSONField(blank=True, null=True)),
                ('cover_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='content.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('author_name', models.CharField(max_length=120)),
                ('author_location', models.CharField(blank=True, default='', max_length=120)),
                ('avatar', models.JSONField(blank=True, null=True)),
                ('quote', models.CharField(max_length=600)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('tour_name', models.CharField(blank=True, default='', max_length=140)),
                ('travelled_on', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='catalog.tour')),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
    ]
