# Generated by Django 6.0.8 on 2026-09-25 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('alt', models.CharField(max_length=300)),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', help_text='Short internal name.', max_length=160)),
                ('source', models.CharField(choices=[('original', 'Original Holidaybank website'), ('pexels', 'Pexels'), ('upload', 'Uploaded in the dashboard'), ('other', 'Other')], db_index=True, default='other', max_length=12)),
                ('photographer', models.CharField(blank=True, default='', max_length=120)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('pexels_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
