# Generated by Django 6.0.8 on 2026-09-25 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('iso_code', models.CharField(blank=True, default='', max_length=2)),
                ('region', models.CharField(choices=[('east-africa', 'East Africa'), ('europe', 'Europe')], db_index=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=180)),
                ('category_label', models.CharField(default='Destination', max_length=60)),
                ('overview', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('best_time', models.JSONField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('seo', models.JSONField(blank=True, null=True)),
                ('card_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='catalog.country')),
                ('hero_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('local', 'Kenyan holiday package'), ('international', 'International holiday'), ('safari', 'Safari')], max_length=20)),
                ('eyebrow', models.CharField(blank=True, default='', max_length=80)),
                ('nav_label', models.CharField(blank=True, default='', help_text='Label in the site menu.', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.tourcategory')),
            ],
            options={
                'verbose_name_plural': 'tour categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('is_sample', models.BooleanField(default=False, help_text='Generated demo content, not information supplied by the business.')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('price_basis', models.CharField(default='per person', max_length=40)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('group_size_max', models.PositiveIntegerField(default=12)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=12)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('location_label', models.CharField(blank=True, default='', max_length=80)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('best_selling', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('seo', models.JSONField(blank=True, null=True)),
                ('parks', models.JSONField(blank=True, default=list)),
                ('game_drive_count', models.PositiveIntegerField(blank=True, null=True)),
                ('conservancy_fees_included', models.BooleanField(blank=True, null=True)),
                ('departs_from', models.CharField(blank=True, default='', max_length=120)),
                ('departure_dates', models.JSONField(blank=True, default=list)),
                ('visa_support', models.BooleanField(blank=True, null=True)),
                ('flights_included', models.BooleanField(blank=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='tours', to='catalog.country')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='catalog.destination')),
                ('hero_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='catalog.tourcategory')),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.imageasset')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='+', through='catalog.TourImage', to='media.imageasset'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('kind', models.CharField(blank=True, default='', help_text='e.g. National reserve, City, Beach', max_length=40)),
                ('blurb', models.CharField(blank=True, default='', max_length=300)),
                ('best_time', models.CharField(blank=True, default='', max_length=120)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='catalog.destination')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.imageasset')),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('destination', 'slug'), name='unique_place_slug_per_destination')],
            },
        ),
        migrations.AddConstraint(
            model_name='tourimage',
            constraint=models.UniqueConstraint(fields=('tour', 'image'), name='unique_tour_gallery_image'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['status', 'featured', 'order'], name='catalog_tou_status_22ae96_idx'),
        ),
    ]
