# Generated by Django 6.0.8 on 2026-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='source_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tour',
            name='source_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='source_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
